name: Weekly Ecosystem Metrics

on:
  schedule:
    - cron: "0 0 * * 1"  

  workflow_dispatch:

permissions:
  contents: write

jobs:
  collect-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run metrics script
        env: 
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: node src2/index.js

      - name: Commit updated metrics
        run: |
          git config --global user.name "Haya Ahmed"
          git config --global user.email "haya.ahm.08@gmail.com"
          git add output/metrics.json
          git commit -m "Update weekly metrics" || echo "No changes"
          git push
